# This workflow will build a Java project with Gradl
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: BackDoor Workflow

on:
  push:
    branches: main

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
 
    - name: Linux Build
      run: |
        mvn install
        mvn package
    - name: Upload The Bruh
      uses: actions/upload-artifact@v2
      with:
        name: backdoor-latest
        path: target/doom*
